import Products from "@/components/home/Products";
import React from "react";
export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const ProductPage = () => {
  return (
    <div>
      <Products></Products>
    </div>
  );
};

export default ProductPage;
